alias wf-facebook="cd ~/Projects/facebook-careers"
alias wf-static="cd ~/Projects/static"
alias brake="bundle exec rake"
alias reset-database="bundle exec rake db:migrate:reset db:test:prepare db:seed"
alias update-vim="curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh"
alias generate-controller-diagram='railroady -C | neato -Tpng > controllers.png'
alias generate-model-diagram='railroady -M | neato -Tpng > models.png'
alias display-controller-diagram='eog controllers.png'
alias display-model-diagram='eog models.png'
alias gd-model-diagram='generate-model-diagram && display-model-diagram'
alias gd-controller-diagram='generate-controller-diagram && display-controller-diagram'
